; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

	TITLE	C:\source\dobot\Win32\Debug\moc\moc_mainwindow.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG139303 DB	'c:\qt\5.13.1\msvc2017\include\qtcore\qmetatype.h', 00H
	ORG $+7
$SG139304 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG139305 DB	'qRegisterNormalizedMetaType', 00H
$SG139640 DB	'c:\qt\5.13.1\msvc2017\include\qtcore\qmetatype.h', 00H
	ORG $+3
$SG139641 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG139642 DB	'qRegisterNormalizedMetaType', 00H
?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_MainWindow
	DD	0aH
	DD	00H
	DD	0c0H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	DD	0bbH
	DD	0ffffffffH
	DD	00H
	DD	00H
	DD	0b9H
	DD	0ffffffffH
	DD	0eH
	DD	00H
	DD	0aaH
	DD	0ffffffffH
	DD	013H
	DD	00H
	DD	0a9H
	DD	0ffffffffH
	DD	05H
	DD	00H
	DD	0adH
	DD	0ffffffffH
	DD	014H
	DD	00H
	DD	0a3H
	DD	0ffffffffH
	DD	013H
	DD	00H
	DD	0a8H
	DD	0ffffffffH
	DD	0eH
	DD	00H
	DD	0acH
	DD	0ffffffffH
	DD	010H
	DD	00H
	DD	0abH
	DD	0ffffffffH
	DD	014H
	DD	00H
	DD	0acH
	DD	0ffffffffH
	DD	011H
	DD	00H
	DD	0b1H
	DB	04dH
	DB	061H
	DB	069H
	DB	06eH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	06fH
	DB	06eH
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	04dH
	DB	06fH
	DB	064H
	DB	065H
	DB	00H
	DB	00H
	DB	06fH
	DB	06eH
	DB	043H
	DB	06fH
	DB	06eH
	DB	06eH
	DB	065H
	DB	063H
	DB	074H
	DB	044H
	DB	06fH
	DB	062H
	DB	06fH
	DB	074H
	DB	00H
	DB	06fH
	DB	06eH
	DB	04aH
	DB	04fH
	DB	047H
	DB	043H
	DB	074H
	DB	072H
	DB	06cH
	DB	042H
	DB	074H
	DB	06eH
	DB	050H
	DB	072H
	DB	065H
	DB	073H
	DB	073H
	DB	065H
	DB	064H
	DB	00H
	DB	069H
	DB	06eH
	DB	064H
	DB	065H
	DB	078H
	DB	00H
	DB	06fH
	DB	06eH
	DB	04aH
	DB	04fH
	DB	047H
	DB	043H
	DB	074H
	DB	072H
	DB	06cH
	DB	042H
	DB	074H
	DB	06eH
	DB	052H
	DB	065H
	DB	06cH
	DB	065H
	DB	061H
	DB	073H
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	050H
	DB	054H
	DB	050H
	DB	073H
	DB	065H
	DB	06eH
	DB	064H
	DB	042H
	DB	074H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	047H
	DB	065H
	DB	074H
	DB	050H
	DB	06fH
	DB	073H
	DB	065H
	DB	054H
	DB	069H
	DB	06dH
	DB	065H
	DB	072H
	DB	00H
	DB	06fH
	DB	06eH
	DB	050H
	DB	075H
	DB	06dH
	DB	070H
	DB	042H
	DB	074H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	048H
	DB	06fH
	DB	06dH
	DB	065H
	DB	053H
	DB	061H
	DB	066H
	DB	065H
	DB	042H
	DB	074H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	050H
	DB	072H
	DB	069H
	DB	06eH
	DB	074H
	DB	042H
	DB	074H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+1
?qt_meta_data_MainWindow@@3QBIB DD 08H			; qt_meta_data_MainWindow
	DD	00H
	DD	00H
	DD	00H
	DD	09H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	03bH
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	03cH
	DD	02H
	DD	08H
	DD	04H
	DD	01H
	DD	03dH
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	040H
	DD	02H
	DD	08H
	DD	07H
	DD	00H
	DD	041H
	DD	02H
	DD	08H
	DD	08H
	DD	00H
	DD	042H
	DD	02H
	DD	08H
	DD	09H
	DD	00H
	DD	043H
	DD	02H
	DD	08H
	DD	0aH
	DD	00H
	DD	044H
	DD	02H
	DD	08H
	DD	0bH
	DD	00H
	DD	045H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02H
	DD	05H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
$SG138966 DB	'c:\qt\5.13.1\msvc2017\include\qtcore\qmetatype.h', 00H
	ORG $+3
$SG138967 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG138968 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@MainWindow@@UBEPBUQMetaObject@@XZ	; MainWindow::metaObject
PUBLIC	?qt_metacast@MainWindow@@UAEPAXPBD@Z		; MainWindow::qt_metacast
PUBLIC	?qt_metacall@MainWindow@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; MainWindow::qt_metacall
PUBLIC	?qt_static_metacall@MainWindow@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; MainWindow::qt_static_metacall
PUBLIC	?staticMetaObject@MainWindow@@2UQMetaObject@@B	; MainWindow::staticMetaObject
EXTRN	_strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
EXTRN	?onChangedMode@MainWindow@@AAEXXZ:PROC		; MainWindow::onChangedMode
EXTRN	?onConnectDobot@MainWindow@@AAEXXZ:PROC		; MainWindow::onConnectDobot
EXTRN	?onJOGCtrlBtnPressed@MainWindow@@AAEXH@Z:PROC	; MainWindow::onJOGCtrlBtnPressed
EXTRN	?onJOGCtrlBtnReleased@MainWindow@@AAEXXZ:PROC	; MainWindow::onJOGCtrlBtnReleased
EXTRN	?onPTPsendBtnClicked@MainWindow@@AAEXXZ:PROC	; MainWindow::onPTPsendBtnClicked
EXTRN	?onGetPoseTimer@MainWindow@@AAEXXZ:PROC		; MainWindow::onGetPoseTimer
EXTRN	?onPumpBtnClicked@MainWindow@@AAEXXZ:PROC	; MainWindow::onPumpBtnClicked
EXTRN	?onHomeSafeBtnClicked@MainWindow@@AAEXXZ:PROC	; MainWindow::onHomeSafeBtnClicked
EXTRN	?onPrintBtnClicked@MainWindow@@AAEXXZ:PROC	; MainWindow::onPrintBtnClicked
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@MainWindow@@2UQMetaObject@@B DB 018H DUP (?) ; MainWindow::staticMetaObject
_BSS	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@MainWindow@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@MainWindow@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'MainWindow::staticMetaObject'', COMDAT
; File c:\source\dobot\win32\debug\moc\moc_mainwindow.cpp
; Line 122
	push	ebp
	mov	ebp, esp
; Line 116
	mov	eax, DWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B, eax
; Line 117
	mov	DWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+4, OFFSET ?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B
; Line 118
	mov	DWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+8, OFFSET ?qt_meta_data_MainWindow@@3QBIB
; Line 119
	mov	DWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+12, OFFSET ?qt_static_metacall@MainWindow@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; MainWindow::qt_static_metacall
; Line 120
	mov	DWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+16, 0
; Line 121
	mov	DWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+20, 0
	pop	ebp
	ret	0
??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'MainWindow::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = -8						; size = 4
__t$1 = -4						; size = 4
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@MainWindow@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; MainWindow::qt_static_metacall
; File c:\source\dobot\win32\debug\moc\moc_mainwindow.cpp
; Line 96
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 97
	cmp	DWORD PTR __c$[ebp], 0
	jne	$LN1@qt_static_
; Line 98
	mov	eax, DWORD PTR __o$[ebp]
	mov	DWORD PTR __t$1[ebp], eax
; Line 100
	mov	ecx, DWORD PTR __id$[ebp]
	mov	DWORD PTR tv69[ebp], ecx
	cmp	DWORD PTR tv69[ebp], 8
	ja	SHORT $LN1@qt_static_
	mov	edx, DWORD PTR tv69[ebp]
	jmp	DWORD PTR $LN16@qt_static_[edx*4]
$LN5@qt_static_:
; Line 101
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?onChangedMode@MainWindow@@AAEXXZ	; MainWindow::onChangedMode
	jmp	SHORT $LN1@qt_static_
$LN6@qt_static_:
; Line 102
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?onConnectDobot@MainWindow@@AAEXXZ	; MainWindow::onConnectDobot
	jmp	SHORT $LN1@qt_static_
$LN7@qt_static_:
; Line 103
	mov	eax, 4
	shl	eax, 0
	mov	ecx, DWORD PTR __a$[ebp]
	mov	edx, DWORD PTR [ecx+eax]
	mov	eax, DWORD PTR [edx]
	push	eax
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?onJOGCtrlBtnPressed@MainWindow@@AAEXH@Z ; MainWindow::onJOGCtrlBtnPressed
	jmp	SHORT $LN1@qt_static_
$LN8@qt_static_:
; Line 104
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?onJOGCtrlBtnReleased@MainWindow@@AAEXXZ ; MainWindow::onJOGCtrlBtnReleased
	jmp	SHORT $LN1@qt_static_
$LN9@qt_static_:
; Line 105
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?onPTPsendBtnClicked@MainWindow@@AAEXXZ	; MainWindow::onPTPsendBtnClicked
	jmp	SHORT $LN1@qt_static_
$LN10@qt_static_:
; Line 106
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?onGetPoseTimer@MainWindow@@AAEXXZ	; MainWindow::onGetPoseTimer
	jmp	SHORT $LN1@qt_static_
$LN11@qt_static_:
; Line 107
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?onPumpBtnClicked@MainWindow@@AAEXXZ	; MainWindow::onPumpBtnClicked
	jmp	SHORT $LN1@qt_static_
$LN12@qt_static_:
; Line 108
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?onHomeSafeBtnClicked@MainWindow@@AAEXXZ ; MainWindow::onHomeSafeBtnClicked
	jmp	SHORT $LN1@qt_static_
$LN13@qt_static_:
; Line 109
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?onPrintBtnClicked@MainWindow@@AAEXXZ	; MainWindow::onPrintBtnClicked
$LN1@qt_static_:
; Line 113
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN16@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
?qt_static_metacall@MainWindow@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; MainWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@MainWindow@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; MainWindow::qt_metacall
; _this$ = ecx
; File c:\source\dobot\win32\debug\moc\moc_mainwindow.cpp
; Line 139
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 140
	mov	eax, DWORD PTR __a$[ebp]
	push	eax
	mov	ecx, DWORD PTR __id$[ebp]
	push	ecx
	mov	edx, DWORD PTR __c$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacall@QMainWindow@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	DWORD PTR __id$[ebp], eax
; Line 141
	cmp	DWORD PTR __id$[ebp], 0
	jge	SHORT $LN2@qt_metacal
; Line 142
	mov	eax, DWORD PTR __id$[ebp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 143
	cmp	DWORD PTR __c$[ebp], 0
	jne	SHORT $LN3@qt_metacal
; Line 144
	cmp	DWORD PTR __id$[ebp], 9
	jge	SHORT $LN5@qt_metacal
; Line 145
	mov	eax, DWORD PTR __a$[ebp]
	push	eax
	mov	ecx, DWORD PTR __id$[ebp]
	push	ecx
	mov	edx, DWORD PTR __c$[ebp]
	push	edx
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	call	?qt_static_metacall@MainWindow@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; MainWindow::qt_static_metacall
	add	esp, 16					; 00000010H
$LN5@qt_metacal:
; Line 146
	mov	ecx, DWORD PTR __id$[ebp]
	sub	ecx, 9
	mov	DWORD PTR __id$[ebp], ecx
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 147
	cmp	DWORD PTR __c$[ebp], 12			; 0000000cH
	jne	SHORT $LN4@qt_metacal
; Line 148
	cmp	DWORD PTR __id$[ebp], 9
	jge	SHORT $LN7@qt_metacal
; Line 149
	mov	edx, 4
	imul	eax, edx, 0
	mov	ecx, DWORD PTR __a$[ebp]
	mov	edx, DWORD PTR [ecx+eax]
	mov	DWORD PTR [edx], -1
$LN7@qt_metacal:
; Line 150
	mov	eax, DWORD PTR __id$[ebp]
	sub	eax, 9
	mov	DWORD PTR __id$[ebp], eax
$LN4@qt_metacal:
; Line 152
	mov	eax, DWORD PTR __id$[ebp]
$LN1@qt_metacal:
; Line 153
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@MainWindow@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; MainWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__clname$ = 8						; size = 4
?qt_metacast@MainWindow@@UAEPAXPBD@Z PROC		; MainWindow::qt_metacast
; _this$ = ecx
; File c:\source\dobot\win32\debug\moc\moc_mainwindow.cpp
; Line 131
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 132
	cmp	DWORD PTR __clname$[ebp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 133
	push	OFFSET ?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B+192
	mov	eax, DWORD PTR __clname$[ebp]
	push	eax
	call	_strcmp
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 134
	mov	eax, DWORD PTR _this$[ebp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 135
	mov	ecx, DWORD PTR __clname$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacast@QMainWindow@@UAEPAXPBD@Z
$LN1@qt_metacas:
; Line 136
	mov	esp, ebp
	pop	ebp
	ret	4
?qt_metacast@MainWindow@@UAEPAXPBD@Z ENDP		; MainWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = -8						; size = 4
_this$ = -4						; size = 4
?metaObject@MainWindow@@UBEPBUQMetaObject@@XZ PROC	; MainWindow::metaObject
; _this$ = ecx
; File c:\source\dobot\win32\debug\moc\moc_mainwindow.cpp
; Line 126
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _this$[ebp], ecx
; Line 127
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	DWORD PTR [eax+24], 0
	je	SHORT $LN3@metaObject
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	ecx, eax
	call	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
	mov	DWORD PTR tv82[ebp], eax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	mov	DWORD PTR tv82[ebp], OFFSET ?staticMetaObject@MainWindow@@2UQMetaObject@@B ; MainWindow::staticMetaObject
$LN4@metaObject:
	mov	eax, DWORD PTR tv82[ebp]
; Line 128
	mov	esp, ebp
	pop	ebp
	ret	0
?metaObject@MainWindow@@UBEPBUQMetaObject@@XZ ENDP	; MainWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File c:\qt\5.13.1\msvc2017\include\qtcore\qscopedpointer.h
; Line 117
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 118
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax]
; Line 119
	mov	esp, ebp
	pop	ebp
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT
; File c:\source\dobot\win32\debug\moc\moc_mainwindow.cpp
; Line 156
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\source\dobot\win32\debug\moc\moc_mainwindow.cpp
; Line 156
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
